name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.16.0
        pnpm-version:
          - 7.9.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Install package and dependencies
        run: bun install

      - name: Run package tests
        run: bun test

      - run: bun index.ts
      - run: bun test --coverage
